#cloud-config
coreos:
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9WsDHltIB7PVFCZQpNkjbBxaWyQeh8ihjw9df5zvZM6TRz80QNM9XceNmjeh0zxocMflnDY19rkeKvy53yd7LFMThand0nLKxgPmsJUM+rkLyOQuDAxEBUWFjSiuxFsWdRYgAFDIaholsLTj9GKiNjntVDXYnHJnvu+g42aaUcq4PKex2meaEDDk6K8xDWj1th2f9GtE5/pWCZZTH7VcTMiX4PrU7EW5guNQdkFRj9a/Hv3ZEwrNWaJvcXIHKFWcA/VyDfrJ4RItTrjIRSJiD6vIZHsQ7mFQsUJOL4IWzE/i38ywgZeDalhlPYwRvFo1zknUwvRieZeSItqq4S7CB bogus@bogus

